# Generated by Django 4.0.5 on 2022-06-02 18:29

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=200)),
                ('numeroTelephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('cin', models.CharField(max_length=20)),
                ('dateNaissance', models.DateField(blank=True, default=0, null=True)),
                ('numeroTelephone', models.CharField(max_length=20)),
                ('sexe', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('motDePasse', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('cin', models.CharField(max_length=20)),
                ('dateNaissance', models.DateField(blank=True, default=0, null=True)),
                ('numeroTelephone', models.CharField(max_length=20)),
                ('sexe', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=200)),
                ('salaire', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('email', models.EmailField(max_length=100)),
                ('motDePasse', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet.cabinet')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 6, 2, 19, 29, 30, 197410))),
                ('maladie', models.CharField(max_length=100)),
                ('consultation', models.CharField(max_length=1000)),
                ('ordonnance', models.CharField(max_length=2000)),
                ('prix', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('prixTotal', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('modePaiement', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet.patient')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreation', models.DateTimeField(default=datetime.datetime(2022, 6, 2, 19, 29, 30, 200549))),
                ('groupeSanguin', models.CharField(max_length=5)),
                ('taille', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('poids', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('assuranceMaladie', models.CharField(max_length=500)),
                ('allergies', models.CharField(blank=True, max_length=2000, null=True)),
                ('vaccination', models.CharField(max_length=2000)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('disponibilite', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet.utilisateur')),
            ],
        ),
    ]
