# Generated by Django 4.0.5 on 2022-06-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0014_alter_dossiermedical_datecreation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermedical',
            name='dateCreation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
