# Generated by Django 4.0.5 on 2022-06-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0015_alter_dossiermedical_datecreation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dateNaissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
