# Generated by Django 4.0.5 on 2022-06-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0016_alter_patient_datenaissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='dateNaissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
