# Generated by Django 4.0.5 on 2022-06-05 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0017_alter_utilisateur_datenaissance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='cabinet',
        ),
        migrations.DeleteModel(
            name='Cabinet',
        ),
    ]
