# Generated by Django 4.0.5 on 2022-06-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0018_remove_utilisateur_cabinet_delete_cabinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='modePaiement',
            field=models.CharField(max_length=1000),
        ),
    ]
